language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"


script:
    - if find . -name "*.eb" -exec python -c "__import__('compiler').parse(open('{}').read())" 2>&1 \; | grep "SyntaxError"; then exit 1; fi
    - if find . -name "*.py" -exec python -c "__import__('compiler').parse(open('{}').read())" 2>&1 \; | grep "SyntaxError"; then exit 1; fi
